### PR TITLE
Update .env

### PR DESCRIPTION
**Pull request by andrewng88**
POSTGRES_HOST=localhost
ELASTIC_URL_LOCAL=http://localhost:9200

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
Not sure about this one. Will it still work for the apps in docker compose?

**Comment by KonuTech** [comment]
ELASTIC_URL_LOCAL=http://localhost:9200 helps to start indexing with Elasticsearch when run prep.py

In my case when:
ELASTIC_URL_LOCAL=http://localhost:9201:
```
python prep.py
Starting the indexing process...
Fetching documents...
Fetched 948 documents
Fetching ground truth data...
Fetched 1830 ground truth records       
Loading model: multi-qa-MiniLM-L6-cos-v1
Setting up Elasticsearch...
Traceback (most recent call last):
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/prep.py", line 106, in <module>  
    main()
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/prep.py", line 95, in main       
    es_client = setup_elasticsearch()
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/prep.py", line 71, in setup_elasticsearch
    es_client.indices.delete(index=INDEX_NAME, ignore_unavailable=True)
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 446, in wrapped
    return api(*args, **kwargs)
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/indices.py", line 736, in delete
    return self.perform_request(  # type: ignore[return-value]
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 423, in perform_request
    return self._client.perform_request(
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 271, in perform_request
    response = self._perform_request(
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 316, in _perform_request
    meta, resp_body = self.transport.perform_request(
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/.venv/lib/python3.10/site-packages/elastic_transport/_transport.py", line 342, in perform_request
    resp = node.perform_request(
  File "/mnt/c/Users/KonuTech/llm-zoomcamp-module-04/.venv/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fc363e9f580>: Failed to establish a new connection: [Errno 111] Connection refused))
```


When:
ELASTIC_URL_LOCAL=http://localhost:9200

```
python prep.py
Starting the indexing process...
Fetching documents...
Fetched 948 documents
Fetching ground truth data...
Fetched 1830 ground truth records
Loading model: multi-qa-MiniLM-L6-cos-v1
Setting up Elasticsearch...
Elasticsearch index 'course-questions' created
Indexing documents...
100%|███████████████████████████████████████████████| 948/948 [01:52<00:00,  8.46it/s]Indexed 948 documents
Initializing database...
Indexing process completed successfully!
```

**Comment by alexeygrigorev** [comment]
Updated `ELASTIC_URL_LOCAL`

**Comment by alexeygrigorev** [comment]
I'll close the PR for now. For pg when running locally, just do this in the terminal

```
export POSTGRES_HOST=localhost
```

**Pull request closed without merging**
